name: Teste de Integração

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências e compilar
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc

      - name: Compilar no Windows
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: gcc -Wall -Wextra -O2 arquivoTeste.c -o programa.exe

      - name: Executar programa no Windows
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: ./programa.exe

      - name: Instalar GCC no Ubuntu
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install -y gcc

      - name: Compilar no Ubuntu
        if: runner.os == 'Linux'
        run: gcc -Wall -Wextra -O2 arquivoTeste.c -o programa

      - name: Executar programa no Ubuntu
        if: runner.os == 'Linux'
        run: ./programa
