name: Teste de Integra

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar compilador C
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compilar o projeto
        run: gcc -Wall -Wextra -O2 arquivoTeste.c -o programa

      - name: Executar o programa compilado
        run: ./programa
