name: Teste de Integração

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar MinGW
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc

      - name: Compilar o projeto
        shell: msys2 {0}
        run: gcc -Wall -Wextra -O2 arquivoTeste.c -o programa.exe

      - name: Executar o programa compilado
        shell: msys2 {0}
        run: ./programa.exe
